name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://ftpupload.net/htdocs/gittest/"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
