# This is a basic workflow to help you get started with Actions
# Give a name for your workflow

name: FTP Deployer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# [workflow_dispatch] --> allows to build manually
# you may use the following to build on each push
# on:
#  push:	
#    branches: [ master ]	

on: [workflow_dispatch]

jobs:
# This workflow contains a single job called "deploy"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://ftpupload.net/htdocs/gittest/"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
